# Generated by Django 5.2.4 on 2025-07-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewsmodels',
            old_name='review_user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='reviewsmodels',
            name='review_rating',
            field=models.FloatField(),
        ),
    ]
