# Generated by Django 5.2.4 on 2025-07-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_reviewsmodels_review_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsmodels',
            name='review_rating',
            field=models.FloatField(),
        ),
    ]
