# Generated by Django 5.2.4 on 2025-07-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('materials', models.TextField(blank=True)),
                ('isHot', models.BooleanField(default=False)),
                ('img1', models.URLField(blank=True, null=True)),
                ('img2', models.URLField(blank=True, null=True)),
                ('img3', models.URLField(blank=True, null=True)),
                ('img4', models.URLField(blank=True, null=True)),
                ('img5', models.URLField(blank=True, null=True)),
                ('specifications', models.TextField(blank=True)),
                ('category', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
