# Generated by Django 5.2.4 on 2025-07-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('chair', 'Chair'), ('table', 'Table'), ('sofa', 'Sofa'), ('bed', 'Bed'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
