# Generated by Django 5.2.4 on 2025-07-28 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='review',
        ),
    ]
